name: "Automated Code Review"

on:
  pull_request:
    types: [opened]
  issue_comment:                                     
    types: [created, edited]

jobs:
  review:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'pull_request' || 
      (github.event_name == 'issue_comment' && contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '#CR'))
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install requests
          pip install -q -U google-genai

      - name: Run Code Review Script
        continue-on-error: true 
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.issue.number || github.event.pull_request.number }}
        run: python .github/scripts/code_review.py
