name: Zanadir Scan

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  zanadir-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Run zanadir Github action
      uses: mustachecase/zanadir-action@v1.7
      with:
        dir: .
        debug: true
        enforce: false
        output: sarif
        output-file: zanadir.sarif

    - name: Upload zanadir SARIF
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: zanadir.sarif
        category: zanadir
